### Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "pedromonteiro@isel.pt",
  "password": "monteiro"
}

### Create user
POST http://localhost:8080/api/users
Authorization: Bearer 7YFdSrXXioNhIBQGvOWCYzcPGOIS1u0uaVuSxxAtSwo=
Content-Type: application/json

{
  "name": "teste",
  "email": "teste@gmail.com",
  "password": "teste",
  "profile": 1
}

### Update user
PUT http://localhost:8080/api/users/2
Authorization: Bearer 7YFdSrXXioNhIBQGvOWCYzcPGOIS1u0uaVuSxxAtSwo=
Content-Type: application/json

{
  "state": "INACTIVE"
}

### Create Shift
POST http://localhost:8080/api/shifts
Authorization: Bearer x_5OB2idVRq7HazHYkt-1oj6euLLZRqVKeEvGOI3bpQ=
Content-Type: application/json

{
  "uid": 1,
  "cid": 1,
  "startTime": "2024-06-01T08:00:00Z",
  "endTime": "2024-06-01T16:00:00Z"
}

### Start Shift
PUT http://localhost:8080/api/shifts/start/1
Authorization: Bearer x_5OB2idVRq7HazHYkt-1oj6euLLZRqVKeEvGOI3bpQ=
Content-Type: application/json

{
  "startTime": "2024-06-20T20:00:00Z"
}

### Create Activity
POST http://localhost:8080/api/activities
Authorization: Bearer ZcosQpeT-9wMCSex4GGX0HJ2Ry50CAKK3tWl3yAAfjk=
Content-Type: application/json

{
  "type": "CLOSE_CABINET",
  "uid": 1
}

### Get page of activities
GET http://localhost:8080/api/activities?page=0&size=2
Authorization: Bearer ZcosQpeT-9wMCSex4GGX0HJ2Ry50CAKK3tWl3yAAfjk=
