### Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "admin@isel.pt",
  "password": "admin"
}

### Create user
POST http://localhost:8080/api/users
Authorization: Bearer 7YFdSrXXioNhIBQGvOWCYzcPGOIS1u0uaVuSxxAtSwo=
Content-Type: application/json

{
  "name": "teste",
  "email": "teste@gmail.com",
  "password": "teste",
  "profile": 1
}

### Update user
PUT http://localhost:8080/api/users/2
Authorization: Bearer 7YFdSrXXioNhIBQGvOWCYzcPGOIS1u0uaVuSxxAtSwo=
Content-Type: application/json

{
  "state": "INACTIVE"
}

### Create Shift
POST http://localhost:8080/api/shifts
Authorization: Bearer x_5OB2idVRq7HazHYkt-1oj6euLLZRqVKeEvGOI3bpQ=
Content-Type: application/json

{
  "uid": 1,
  "cid": 1,
  "startTime": "2024-06-01T08:00:00Z",
  "endTime": "2024-06-01T16:00:00Z"
}

### Start Shift
PUT http://localhost:8080/api/shifts/start/1
Authorization: Bearer x_5OB2idVRq7HazHYkt-1oj6euLLZRqVKeEvGOI3bpQ=
Content-Type: application/json

{
  "startTime": "2024-06-20T20:00:00Z"
}