# Configuration of the test database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=tubarao
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
